[project]
name = "clix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "distrax>=0.1.5",
    "flax>=0.10.6",
    "jax>=0.6.0",
    "jupyterlab>=4.4.2",
    "optax>=0.2.4",
    "pandas>=2.2.3",
    "progress-table>=3.1.2",
    "pytest>=8.3.5",
    "rax>=0.4.0",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
]
