defaults:
  - _self_
  - parameter/examination: position
  - parameter/attraction: embedding/robe-d
  - parameter/satisfaction: embedding/robe-d
  - model: ubm

random_state: 42
query_doc_pairs: 120_000_000
positions: 10
