defaults:
  - _self_
  - dataset: baidu-ultr
  - parameter/examination: position
  - parameter/attraction: embedding/hash
  - parameter/satisfaction: embedding/hash
  - model: pbm


random_state: 42

# To be overwritten by specific datasets:
query_doc_pairs: ???
train_sessions: ???
val_sessions: ???
test_sessions: ???

train_batch_size: 512
eval_batch_size: 512
positions: 10

compression_ratio: 1000
experiment: ""
