defaults:
  - _self_
  - parameter/examination: position
  - parameter/attraction: embedding/hash
  - parameter/satisfaction: embedding/hash
  - model: pbm


random_state: 42
query_doc_pairs: 130_000_000
batch_size: 512
positions: 10

dataset: data/wscd-2012/YandexClicks.txt
experiment: ""
