# @package _global_

dataset:
  _target_: clax.datasets.BaiduULTRDataset
  path: /fnwi_fs/ivi/irlab/datasets/clax-datasets/baidu_ultr_embeddings/
  max_positions: 10

query_doc_pairs: 1_300_000_000
train_sessions: [0, 1_000_000_000]
val_sessions: [1_000_000_000, 1_100_000_000]
test_sessions: [1_000_000_000, 1_100_000_000]
