# @package _global_

dataset:
  _target_: clax.datasets.ParquetDataset
  source: "${dataset_dir}/yandex"
  max_positions: 10

query_doc_pairs: 130_000_000

train_sessions: [0, 100_000_000]
val_sessions: [100_000_000, 123_000_000]
test_sessions: [123_000_000, 146_000_000]
